#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DP-0 -d I II III
bspc monitor DP-4 -d IV V VI VII VIII IX X
bspc monitor DP-2 -d

bspc config border_radius 3
bspc config border_width 3
bspc config window_gap 10
bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color '#7b05b5'
bspc config urgent_border_color '#dd2727'

bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a firefox desktop='^10' follow=on focus=on
bspc rule -a discord desktop='^3' follow=on
bspc rule -a 'Spotify' desktop='^2' follow=on
bspc rule -a 'thunderbird' desktop='^2'
bspc rule -a KeePassXC state=floating
bspc rule -a org.gnome.Nautilus state=floating
bspc rule -a 'qBittorrent' desktop='^8'
bspc rule -a 'notion-app' desktop='^8'
bspc rule -a 'Nemo' state=floating
bspc rule -a 'File-roller' state=floating
bspc rule -a 'TelegramDesktop' state=floating
bspc rule -a 'Galculator' state=floating
bspc rule -a 'Pavucontrol' state=floating
bspc rule -a 'Nvidia-settings' state=floating
bspc rule -a 'steam' state=floating desktop='^5'
bspc rule -a 'steamwebhelper' state=floating desktop='^5'
bspc rule -a 'Hexchat' desktop="^7" follow=on
bspc rule -a 'VirtualBox Manager' desktop="^6" follow=on state=floating
bspc rule -a 'VirtualBox' desktop="^6" follow=on state=floating
bspc rule -a 'Brave-browser' desktop="^9"

xrandr --output DP-0 --rotate right --mode 1920x1080 --rate 60 --pos 0x0 --output DP-4 --primary --rotate normal --mode 1920x1080 --rate 165 --pos 1080x420 --output DP-2 --rotate normal --mode 1920x1080 --rate 165 --pos 3000x420
xrdb $HOME/.Xresources
$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/autostart.sh
$HOME/.config/.fehbg
